### PR TITLE
Cleanup `lighttpd_rust_amalgamated` into a single `src/main.rs`

### PR DESCRIPTION
**Pull request by kkysen**
Cleanup `lighttpd_rust_amalgamated` into a single `src/main.rs` with a simple `Cargo.toml` so that it can be run with `c2rust-analyze` easily, just like in #6.  The difference is that these changes are a bit more minimal and modern (e.x. edition 2021), but still work with `c2rust-analyze` if the same `rustc` arguments (as seen from `cargo build --verbose`) are used.

### CODE REVIEW

**Comment by oinoom** [comment]
Does this replace #6? Why wasn't that PR contributed to instead?

**Comment by kkysen** [comment]
I was exploring the `--edition 2021` thing and whether all the `extern crate` and `#[macro_use]`s in #6 were necessary (they aren't), and came up with this during that exploration.  It could be used in place of #6 minus the script, and also comes with the benefit that it is generated by `./amalgamate.sh`, so if we need to tweak that later (e.x. to add in more modules statically, or something else), it'll work out of the box.

**Comment by oinoom** [comment]
I think this should be consolidated with #6, a change of base to that is fine. the primary lift in this PR is editing the `main.rs` output. I've also tried to test static analysis with the output of this branch and it couldn't find `libc` things in `main.rs` (unless I ran it incorrectly). #6 does not have this issue

**Comment by kkysen** [comment]
That's odd.  It ran fine when I copied the arguments from `cargo build --verbose`.  Specifically, I ran:

```sh
kkysen in 🌐 donna in lighttpd/lighttpd_rust_amalgamated on  kkysen/cleanup-amalgamated is 📦 v0.1.0 via 🦀 v1.65.0-nightly via 🐏 4GiB/63GiB | 16MiB/2GiB took 1s58ms
at 02:56:06 PM ❯ ../../c2rust/target/release/c2rust-analyze --sysroot "$(rustc --print sysroot)" --crate-name lighttpd_rust_amalgamated --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=b79bd91ecb9d50fb -C extra-filename=-b79bd91ecb9d50fb --out-dir /home/kkysen/work/rust/lighttpd/lighttpd_rust_amalgamated/target/debug/deps -C linker=clang -C incremental=/home/kkysen/work/rust/lighttpd/lighttpd_rust_amalgamated/target/debug/incremental -L dependency=/home/kkysen/work/rust/lighttpd/lighttpd_rust_amalgamated/target/debug/deps --extern c2rust_bitfields=/home/kkysen/work/rust/lighttpd/lighttpd_rust_amalgamated/target/debug/deps/libc2rust_bitfields-777dd448e2307781.rlib --extern libc=/home/kkysen/work/rust/lighttpd/lighttpd_rust_amalgamated/target/debug/deps/liblibc-6fc9a51e0719cc75.rlib -C link-arg=-fuse-ld=/home/kkysen/work/c++/mold/current/bin/mold -A warnings -l pcre2-8 -l crypt -C link-arg=-Wl,-export-dynamic
```

which is `c2rust-analyze --sysroot "$(rustc --print sysroot)"` plus the post-`rustc` args that `cargo build --verbose` prints.

Update: `--sysroot "$(rustc --print sysroot)"` works in place of `-L "$(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/lib"`.

**Comment by kkysen** [comment]
> the primary lift in this PR is editing the `main.rs` output.

It merges everything into `main.rs` and makes the `Cargo.toml` an idiomatic (`cargo`-generated) one.  I think if we rebase the script-related commits from #6, c66cfb8e9644bc2e54671021ec91d56ad1085fa4..8de93f4a8fd9db3e3cc17fecd9e6bf39c1ff3717, that would incorporate all the changes we need for static analysis.

**Comment by kkysen** [comment]
As a slightly trimmed command, this seems to work:

```sh
../../c2rust/target/release/c2rust-analyze --sysroot "$(rustc --print sysroot)" --crate-name lighttpd_rust_amalgamated --edition=2021 src/main.rs --crate-type bin -L dependency=target/debug/deps --extern c2rust_bitfields=target/debug/deps/libc2rust_bitfields-777dd448e2307781.rlib --extern libc=target/debug/deps/liblibc-6fc9a51e0719cc75.rlib -A warnings -l pcre2-8 -l crypt -C link-arg=-Wl,-export-dynamic
```

**Review by oinoom — APPROVED** [review]

**Pull request merged**
