### PR TITLE
Some small improvements to the `c2rust-analyze` on `lighttpd_rust_amalgamated` script

### PR DESCRIPTION
**Pull request by kkysen**
`cargo` also sets `--crate-type bin`, not `--crate-type rlib`, but I think that difference is okay, as `c2rust-analyze` doesn't need to compile all the way to a binary, and doing so would mean we'd also have to pass the link args: `-l pcre2-8 -l crypt -C link-arg=-Wl,-export-dynamic`.

### CODE REVIEW

**Comment by oinoom** [comment]
tested?

**Comment by kkysen** [comment]
Yeah, the script still works if you run it with no args from the `c2rust` directory.

**Review by oinoom — DISMISSED** [review]

**Comment by oinoom** [comment]
wait, before you merge, how does it know where to find lighttpd-rust-amalgamated if run from the c2rust dir?

**Comment by kkysen** [comment]
> wait, before you merge, how does it know where to find lighttpd-rust-amalgamated if run from the c2rust dir?

It uses `$0`, which is the path of the script being run, and just gets its directory.

**Review by oinoom — APPROVED** [review]

**Pull request merged**
